spring:
  datasource:
    url: jdbc:mysql://39.97.255.201:3306/JavaWeb?useUnicode=true&characterEncoding=UTF-8
    username: javaweb
    password: 585658
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: ture
server:
  port: 8181

